#
# Here's the library we're compiling.  By default, we build the arduino 
# library.  To build the other arduino libraries, we need to override 
# LIB, HDR, C_SRC and CPP_SRC.
#
LIBDIR=../../lib
LIB=arduino

# Set compiler settings.
CC=avr-gcc
CXX=avr-g++
AR=avr-ar
MMCU=atmega328p
MHZ=16


INC_DIRS := -I .
 
CFLAGS  := -Wall -Os
CFLAGS += -mmcu=$(MMCU) -DF_CPU=$(MHZ)000000   # Arduino Uno
CFLAGS  += $(INC_DIRS)
 
CXXFLAGS := -Wall -Os
CXXFLAGS += -mmcu=$(MMCU) -DF_CPU=$(MHZ)000000   # Arduino Uno
CXXFLAGS += $(INC_DIRS)
 

# Set the source files.
HDR     := binary.h HardwareSerial.h pins_arduino.h Print.h Stream.h WConstants.h wiring.h wiring_private.h WProgram.h WString.h
C_SRC   := pins_arduino.c wiring_analog.c wiring_digital.c wiring_shift.c wiring.c wiring_pulse.c WInterrupts.c
CPP_SRC := HardwareSerial.cpp Tone.cpp WString.cpp  Print.cpp  WMath.cpp
OBJ := $(C_SRC:.c=.o) $(CPP_SRC:.cpp=.o)


# Build the library.
$(LIB): $(OBJ) $(C_SRC) $(CPP_SRC) $(HDR)
	$(AR) rcs $(LIBDIR)/lib$(LIB).a $(OBJ)


all: $(LIB)
 
clean:
	@rm -rfv *.o
	@rm -rfv *.a
