#!/bin/sh
#
#        Copyright (C) 2011 Shawn Wilson
#        shawn@ch2a.ca
#        
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This script will compile a pde file using the arduino libraries.
# It automatically creates a build environment and chooses the right
# include files and libraries.

# PARAMETERS
PDE_FILE=$1
PROGRAM=${PDE_FILE%.pde}

# Make sure we have a file to compile.
if [ "${PROGRAM}" = "" ] ; then
   echo
   echo Usage: `basename $0` \<filename.pde\>
   echo
   exit 1
fi

# Include useful functions and all directory paths.
prefix=`pwd`/install
#prefix=@prefix@
. ../lib/init-functions
#. @datadir@/@PACKAGE@/init-functions



#######
# main section
#######

##### Set up the program sources for compiling #####

# Make the source directory and add a symlink to the pde file.
mkdir -p $arduino_srcdir
cp ${datadir}/main.c $arduino_srcdir
ln -f -s `abspath $PDE_FILE` ${arduino_srcdir}/arduino_program.pde

# Scan the pde file for relative headers and make symlinks
# to the files in the src directory so it compiles properly.
for file in `relhdrs $PDE_FILE` ; do 
   ln -s `abspath $file` ${arduino_srcdir}/${PROGRAM}
done

# Copy over the custom make file.
cp ${datadir}/Makefile.pde ${arduino_srcdir}/${PROGRAM}/Makefile


######### Make the program ########

echo "Cross compiling..."
#make -C LIBDIR=${arduino_srcdir}/${PROGRAM} INCDIR=${arduino_includedir}


# Check to make sure it finished successfully.
if [ -f ${arduino_srcdir}/${PROGRAM}/arduino_program.hex ];
then
   echo
   echo "Success!!"
   echo
   exit 0
else
   echo  
   echo "Something broke - cannot find ${arduino_localstatedir}/arduino_program.hex."
   echo
   exit 1
fi
