#!/bin/sh
#
#        Copyright (C) 2011 Shawn Wilson
#        shawn@ch2a.ca
#        
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# This script is used for building libarduino.a from the arduino web site.
# It will download the code, extract it and make all the libraries.
# 


# Include useful functions and all directory paths.
prefix=.
. ../data/init-functions


# Create the working directories if necessary.
mkdir -p $arduino_libdir $arduino_localstatedir \
   $arduino_srcdir $arduino_includedir



########## Set up arduino sources ############

# Check to see if we can use the built-in distro copy of arduino.
grep --silent -i -e "Ubuntu 11.10" -e "Ubuntu 11.04" /etc/lsb-release
ARDUINO_PACKAGE=$?

echo "Getting arduino source code and installing compile tools..."
echo

# If there's no built-in arduino package, download from source.
if [ $ARDUINO_PACKAGE -eq 1 ] ; then

   # Check for 64 or 32 bit
   if [ `uname -m` = "x86_64" ] ; then
      PKGNAME="arduino-0022-64-2"
   else
      PKGNAME="arduino-0022"  
   fi
   PKG_URL="http://arduino.googlecode.com/files/${PKGNAME}.tgz"


   #
   # Put the arduino sources in the source directory.
   #
   CURDIR=`pwd`
   cd /tmp

   # Download arduino sources from the web and put them in the src
   # direcory.
   if [ ! -e /tmp/${PKGNAME}.tgz ] ; then
      wget $PKG_URL
      tar zxvf ${PKGNAME}.tgz
   fi

   mv ${PKGNAME}/* $arduino_srcdir
   cd $CURDIR
   exit 0


else
   echo "Installing the arduino package..."
   sudo apt-get -y install arduino

   # Since the package is already installed, we just point to the
   # shared data with symbolic links.
   ln -s /usr/share/arduino/* $arduino_srcdir 
fi



######## Set up the build directory #########

# Create links to the files in the source directory.
ln -s ${arduino_srcdir}/hardware/arduino/cores/arduino/* \
   $arduino_localstatedir 
ln -s ${arduino_srcdir}/hardware/arduino/cores/arduino/*.h \
   $arduino_includedir 

# Copy over the custom make file.
rm $arduino_localstatedir/Makefile
cp ${datadir}/Makefile.lib $arduino_localstatedir/Makefile



######### Make the libraries ########

echo "Installing gcc-avr, avr-libc and avrdude if necessary..."
sudo apt-get -y install gcc-avr avr-libc avrdude

echo "Making libarduino..."
make -C $arduino_localstatedir


# Check to make sure it finished successfully.
if [ -f ${arduino_libdir}/libarduino.a ];
then
   echo
   echo "Success!!"
   echo
   exit 0
else
   echo  
   echo "Something broke - cannot find libarduino/libarduino.a."
   echo
   exit 1
fi
